### PR TITLE
samples: sid_end_device: update nRF5340 IPC

### PR DESCRIPTION
**Pull request by gmarull**
icbmsg is used now, so align.

## CI parameters

```yaml
Github_actions:
  #(branch, hash, pull/XXX/head)
  NRF_revision: pull/17721/head

  # Do not change after creating PR
  Create_NRF_PR: false
Jenkins:
  test-sdk-sidewalk: master
```

## Description

JIRA ticket: 

## Self review

- [x] There is no commented code.
- [x] There are no TODO/FIXME comments without associated issue ticket.
- [x] Commits are properly organized.
- [ ] Change has been tested.
- [x] Tests were updated (if applicable).

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Review by ktaborowski — CHANGES_REQUESTED** [review]
Regressinon in BLE start on nRF5340
```
<inf> sid_ble: Enable BT
ASSERTION FAIL [len <= sizeof(rx_buffer)] @ ../../../../../zephyr/subsys/ipc/ipc_service/lib/icmsg.c:190
```

**Comment by totyz** [comment]
@gmarull - could you rebase this PR on the newest sdk-sidewalk main?
The nrf5340 on this PR looks okay, but our tests fail due to a problem with nrf52. These problems were just fixed and are on the main branch.
Thanks

**Comment by gmarull** [comment]
> @gmarull - could you rebase this PR on the newest sdk-sidewalk main? The nrf5340 on this PR looks okay, but our tests fail due to a problem with nrf52. These problems were just fixed and are on the main branch. Thanks

done

**Comment by totyz** [comment]
@gmarull 
the assert is still visible:
```
2024-10-14 14:37:43.394929: uart:~$ *** Booting Sidewalk v2.7.99-ca65514747d4 ***
2024-10-14 14:37:43.396298: uart:~$ *** Using nRF Connect SDK v2.7.99-d6abf707f456 ***
2024-10-14 14:37:43.397507: uart:~$ *** Using Zephyr OS v3.7.99-f6e525166e4f ***
2024-10-14 14:37:43.398868: uart:~$ ----------------------------------------------------------------
2024-10-14 14:37:43.400144: uart:~$ Sidewalk SDK        = 1.16.1.28
2024-10-14 14:37:43.406651: uart:~$ APP_BUILD_VERSION   = ca65514747d4
2024-10-14 14:37:43.422121: uart:~$ build time          = Oct 14 2024 10:32:46
2024-10-14 14:37:43.424907: uart:~$ board               = nrf5340dk/nrf5340/cpuapp
2024-10-14 14:37:43.426742: uart:~$ ----------------------------------------------------------------
2024-10-14 14:37:43.528226: uart:~$ [00:00:00.036,651] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
2024-10-14 14:37:43.531207: uart:~$ [00:00:00.036,682] <inf> bt_hci_core: HW Variant: nRF53x (0x0003)
2024-10-14 14:37:43.534399: uart:~$ [00:00:00.036,712] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 44.56992 Build 212516553
2024-10-14 14:37:43.537124: uart:~$ [00:00:00.039,062] <inf> bt_hci_core: Identity: F0:44:89:48:81:41 (random)
2024-10-14 14:37:43.548276: uart:~$ [00:00:00.039,093] <inf> bt_hci_core: HCI: version 6.0 (0x0e) revision 0x202a, manufacturer 0x0059
2024-10-14 14:37:43.550804: uart:~$ [00:00:00.039,123] <inf> bt_hci_core: LMP: version 6.0 (0x0e) subver 0x202a
2024-10-14 14:37:47.509960: uart:~$ uart:~$ sid init 1
2024-10-14 14:37:47.511040: uart:~$ [00:00:04.103,881] <dbg> sid_ble: ble_adapter_init: Sidewalk -> BLE
2024-10-14 14:37:47.511785: uart:~$ [00:00:04.103,912] <inf> sid_ble: Enable BT
2024-10-14 14:37:47.512477: uart:~$ ASSERTION FAIL [len <= sizeof(rx_buffer)] @ ../../../../../zephyr/subsys/ipc/ipc_service/lib/icmsg.c:190
2024-10-14 14:37:47.513267: uart:~$ [00:00:04.118,377] <err> os: r0/a1:  0x00000004  r1/a2:  0x000000be  r2/a3:  0x00000003
2024-10-14 14:37:47.513995: uart:~$ [00:00:04.118,408] <err> os: r3/a4:  0x00000004 r12/ip:  0x00000014 r14/lr:  0x00011d71
2024-10-14 14:37:47.514705: uart:~$ [00:00:04.118,408] <err> os:  xpsr:  0x01000000
2024-10-14 14:37:47.515481: uart:~$ [00:00:04.118,408] <err> os: s[ 0]:  0x6c000000  s[ 1]:  0x72304b31  s[ 2]:  0x696c336e  s[ 3]:  0x00000034
2024-10-14 14:37:47.527537: uart:~$ [00:00:04.118,438] <err> os: s[ 4]:  0x007fffff  s[ 5]:  0x20003c80  s[ 6]:  0x00000020  s[ 7]:  0x00000022
2024-10-14 14:37:47.528591: uart:~$ [00:00:04.118,438] <err> os: s[ 8]:  0xffffffff  s[ 9]:  0x00000000  s[10]:  0x20005af8  s[11]:  0x0002c839
2024-10-14 14:37:47.545230: uart:~$ [00:00:04.118,469] <err> os: s[12]:  0x200058e8  s[13]:  0x20007fb0  s[14]:  0xffffffff  s[15]:  0x0002becd
2024-10-14 14:37:47.549888: uart:~$ [00:00:04.118,469] <err> os: fpscr:  0x20007fb0
2024-10-14 14:37:47.651241: uart:~$ [00:00:04.118,499] <err> os: r4/v1:  0x20002060  r5/v2:  0x20002070  r6/v3:  0x00000002
2024-10-14 14:37:47.652874: uart:~$ [00:00:04.118,499] <err> os: r7/v4:  0x00000000  r8/v5:  0xffffffff  r9/v6:  0xffffffff
2024-10-14 14:37:47.653822: uart:~$ [00:00:04.118,499] <err> os: r10/v7: 0x00000000  r11/v8: 0x00000000    psp:  0x20010dc0
2024-10-14 14:37:47.654693: uart:~$ [00:00:04.118,530] <err> os: EXC_RETURN: 0x0
2024-10-14 14:37:47.661195: uart:~$ [00:00:04.118,530] <err> os: Faulting instruction address (r15/pc): 0x00050cb8
2024-10-14 14:37:47.662078: uart:~$ [00:00:04.118,560] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
2024-10-14 14:37:47.662976: uart:~$ [00:00:04.118,591] <err> os: Current thread: 0x20003b50 (icmsg_workq)
2024-10-14 14:37:47.668971: uart:~$ [00:00:04.313,018] <err> os: Halting system
```

**Comment by RobertGalatNordic** [comment]
For some odd reason, I can not find the actual value generated for the build for the Kconfig PBUF_RX_READ_BUF_SIZE.

I suspect this is the cause of the assert error. When we look at the assert, we actually fail if `len` is bigger than an rx_buffer, and the last one is a static global array, with size defined by the mentioned KConfig. 

I was able to locate the Kconfig definition, and I can see that the default value is 128, but, I could not find it in any of the generated .config files, therefore I suspect that for some odd reason, this didn't get picked up, and ended up with some invalid size. 

(I used grep to search the whole build directory `grep -r "PBUF_RX_READ_BUF_SIZE" build` and got nothing, so I suspect that this may be important to figure out this bug)

**Comment by RobertGalatNordic** [comment]
the assert states, that `len` is bigger than the rx_buffer size. Therefore we have to belive it is true. The rx_buffer is 128 bytes.

It is hard to track how big is the actual queue that we read from, but it seems that when we read the number of bytes in the queue in 
[static uint32_t data_available(struct icmsg_data_t *dev_data)](https://github.com/nrfconnect/sdk-zephyr/blob/d3d3f66845737630687c9018cdb687319b74ec17/subsys/ipc/ipc_service/lib/icmsg.c#L122-L125)

We get value bigger than 128.

So the issue may be with the handling of bigger than expected payloads, or with putting too big payloads, or with corruption of the data ( we read incorrect size) I do not really know, this needs further investigation.

I will try to build and run Sidewalk sample under debugger, and try to catch what value of `len` is returned when we trigger the assert. 

But if my suspisions are correct, it should be possible to create a test, where we put element bigger than 128, and on the `mbox_callback_process` attempt we will get the same assert.

**Comment by RobertGalatNordic** [comment]
I added log before the assert to track the readed `len` value, and got following result
```
ASSERTION FAIL [len <= sizeof(rx_buffer)] @ WEST_TOPDIR/zephyr/subsys/ipc/ipc_service/lib/icmsg.c:191
        len was 62992
[00:00:00.279,968] <err> os: r0/a1:  0x00000004  r1/a2:  0x000000bf  r2/a3:  0x0000000c
[00:00:00.279,998] <err> os: r3/a4:  0x00000004 r12/ip:  0x0000000c r14/lr:  0x0000f32f
[00:00:00.279,998] <err> os:  xpsr:  0x21000000
[00:00:00.279,998] <err> os: s[ 0]:  0x6c000000  s[ 1]:  0x72304b31  s[ 2]:  0x696c336e  s[ 3]:  0xffffff34
[00:00:00.280,029] <err> os: s[ 4]:  0xffffffff  s[ 5]:  0x00000022  s[ 6]:  0x007fffff  s[ 7]:  0x20003750
[00:00:00.280,029] <err> os: s[ 8]:  0x00000020  s[ 9]:  0x00000022  s[10]:  0xffffffff  s[11]:  0x00000000
[00:00:00.280,059] <err> os: s[12]:  0x20004ec8  s[13]:  0x00025ab5  s[14]:  0x20004d18  s[15]:  0x20006824
[00:00:00.280,059] <err> os: fpscr:  0xffffffff
[00:00:00.280,059] <err> os: r4/v1:  0x20002060  r5/v2:  0x0000f610  r6/v3:  0x20002070
[00:00:00.280,090] <err> os: r7/v4:  0x00000002  r8/v5:  0xffffffff  r9/v6:  0xffffffff
[00:00:00.280,090] <err> os: r10/v7: 0x00000000  r11/v8: 0x00000000    psp:  0x2000f0c8
[00:00:00.280,090] <err> os: EXC_RETURN: 0x0
[00:00:00.280,090] <err> os: Faulting instruction address (r15/pc): 0x000477c2
[00:00:00.280,120] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:00.280,151] <err> os: Current thread: 0x200038e8 (unknown)
[00:00:00.447,509] <err> os: Halting system
```

So the len is 62992 !!! This definitely does not feel right.

and such big value suggest that some kind of curruption occured, and some payload is treated as length.

**Pull request closed without merging**
