### PR TITLE
Fix zephyr upmerge 2023 12 11

### PR DESCRIPTION
**Pull request by RobertGalatNordic**
before merge change revision of NRF in manifest to the commit hash of merged zephyr upmerge (https://github.com/nrfconnect/sdk-nrf/pull/12619/)

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Comment by nordicjm** [comment]
@RobertGalatNordic safe to merge this/remove DNM tag?

**Comment by de-nordic** [comment]
> @RobertGalatNordic safe to merge this/remove DNM tag?

There is manifest update needed in this PR! There is PR referenced instead of SHA, I do not think this is ok.

**Comment by de-nordic** [comment]
> > @RobertGalatNordic safe to merge this/remove DNM tag?
> 
> There is manifest update needed in this PR! There is PR referenced instead of SHA, I do not think this is ok.

Heh, OK. Seems there is repo reference loop?

**Review by de-nordic — APPROVED** [review]

**Comment by RobertGalatNordic** [comment]
> > > @RobertGalatNordic safe to merge this/remove DNM tag?
> > 
> > 
> > There is manifest update needed in this PR! There is PR referenced instead of SHA, I do not think this is ok.
> 
> Heh, OK. Seems there is repo reference loop?

Sidewalk is hidden behind the group filter, and the internal_west.yml is used without this filter enable only for internal tests

**Pull request merged**
