### PR TITLE
pal: Remove MTU request from nRF to gateway

### PR DESCRIPTION
**Pull request by ktaborowski**
[KRKNWK-17600]
Disable client features, including att mtu requests. Now the MTU request are made by gateway, nRF responds. It is observed the connection with gateway works better this way.

This PR reverts changes form https://github.com/nrfconnect/sdk-sidewalk/pull/235

[KRKNWK-17600]: https://nordicsemi.atlassian.net/browse/KRKNWK-17600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ktaborowski** [comment]
Converted to draft, the mobile app registration fails

**Review by RobertGalatNordic — APPROVED** [review]

**Review by totyz — APPROVED** [review]
The test shows no regression on nrf52.
The BLE communication on nrf53 is much more stable

**Comment by ktaborowski** [comment]
A minimal subset of changes moved from playground branch to https://github.com/nrfconnect/sdk-sidewalk/pull/402
This PR to be closed if the above one merged

**Comment by ktaborowski** [comment]
To be investigated in KRKNWK-17711

**Pull request closed without merging**
